package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Documento implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Fecha")
	private java.util.Date fecha;
	@org.kie.api.definition.type.Label("Identificador Documentos de Soporte")
	private java.lang.Integer soporteDocumentoID;
	@org.kie.api.definition.type.Label("Fecha de notificacion")
	private java.util.Date fechaNotificacion;
	@org.kie.api.definition.type.Label("Forma de Notificacion")
	private java.lang.String modoNotificacion;
	@org.kie.api.definition.type.Label("Numero de Documento")
	private java.lang.String numeroDocumento;
	@org.kie.api.definition.type.Label("Notificacion de Persona")
	private java.lang.String personaNotificacion;
	@org.kie.api.definition.type.Label("Observaciones de Notificacion")
	private java.lang.String observacionNotificacion;
	@org.kie.api.definition.type.Label("Identificador Almacenamiento Documentos")
	private java.lang.String IDRepositorioDocumentos;
	@org.kie.api.definition.type.Label("Identificador Notificacion de Persona")
	private java.lang.String IDPersonaNotificacion;
	@org.kie.api.definition.type.Label("Identificador Documento Autorizado")
	private java.lang.Integer autorizacionDocumentoID;
	@org.kie.api.definition.type.Label("Tipo de persona Autorizada")
	private java.lang.String tipoIDPersonaAutorizacion;
	@org.kie.api.definition.type.Label("Identificador Persona Autorizada")
	private java.lang.String IDPersonaAutorizacion;
	@org.kie.api.definition.type.Label("Nombre Persona Autorizada")
	private java.lang.String personaAutorizacion;
	@org.kie.api.definition.type.Label("Informacion Ingreso Usuario")
	private java.lang.String usuarioLog;
	@org.kie.api.definition.type.Label("Informacion Fecha de ingreso")
	private java.util.Date fechaLog;

	@org.kie.api.definition.type.Label("Identificador")
	private java.lang.Integer ID;

	public Documento() {
	}

	public java.util.Date getFecha() {
		return this.fecha;
	}

	public void setFecha(java.util.Date fecha) {
		this.fecha = fecha;
	}

	public java.lang.Integer getSoporteDocumentoID() {
		return this.soporteDocumentoID;
	}

	public void setSoporteDocumentoID(java.lang.Integer soporteDocumentoID) {
		this.soporteDocumentoID = soporteDocumentoID;
	}

	public java.util.Date getFechaNotificacion() {
		return this.fechaNotificacion;
	}

	public void setFechaNotificacion(java.util.Date fechaNotificacion) {
		this.fechaNotificacion = fechaNotificacion;
	}

	public java.lang.String getModoNotificacion() {
		return this.modoNotificacion;
	}

	public void setModoNotificacion(java.lang.String modoNotificacion) {
		this.modoNotificacion = modoNotificacion;
	}

	public java.lang.String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(java.lang.String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	public java.lang.String getPersonaNotificacion() {
		return this.personaNotificacion;
	}

	public void setPersonaNotificacion(java.lang.String personaNotificacion) {
		this.personaNotificacion = personaNotificacion;
	}

	public java.lang.String getObservacionNotificacion() {
		return this.observacionNotificacion;
	}

	public void setObservacionNotificacion(
			java.lang.String observacionNotificacion) {
		this.observacionNotificacion = observacionNotificacion;
	}

	public java.lang.String getIDRepositorioDocumentos() {
		return this.IDRepositorioDocumentos;
	}

	public void setIDRepositorioDocumentos(
			java.lang.String IDRepositorioDocumentos) {
		this.IDRepositorioDocumentos = IDRepositorioDocumentos;
	}

	public java.lang.String getIDPersonaNotificacion() {
		return this.IDPersonaNotificacion;
	}

	public void setIDPersonaNotificacion(java.lang.String IDPersonaNotificacion) {
		this.IDPersonaNotificacion = IDPersonaNotificacion;
	}

	public java.lang.Integer getAutorizacionDocumentoID() {
		return this.autorizacionDocumentoID;
	}

	public void setAutorizacionDocumentoID(
			java.lang.Integer autorizacionDocumentoID) {
		this.autorizacionDocumentoID = autorizacionDocumentoID;
	}

	public java.lang.String getTipoIDPersonaAutorizacion() {
		return this.tipoIDPersonaAutorizacion;
	}

	public void setTipoIDPersonaAutorizacion(
			java.lang.String tipoIDPersonaAutorizacion) {
		this.tipoIDPersonaAutorizacion = tipoIDPersonaAutorizacion;
	}

	public java.lang.String getIDPersonaAutorizacion() {
		return this.IDPersonaAutorizacion;
	}

	public void setIDPersonaAutorizacion(java.lang.String IDPersonaAutorizacion) {
		this.IDPersonaAutorizacion = IDPersonaAutorizacion;
	}

	public java.lang.String getPersonaAutorizacion() {
		return this.personaAutorizacion;
	}

	public void setPersonaAutorizacion(java.lang.String personaAutorizacion) {
		this.personaAutorizacion = personaAutorizacion;
	}

	public java.lang.String getUsuarioLog() {
		return this.usuarioLog;
	}

	public void setUsuarioLog(java.lang.String usuarioLog) {
		this.usuarioLog = usuarioLog;
	}

	public java.util.Date getFechaLog() {
		return this.fechaLog;
	}

	public void setFechaLog(java.util.Date fechaLog) {
		this.fechaLog = fechaLog;
	}

	public java.lang.Integer getID() {
		return this.ID;
	}

	public void setID(java.lang.Integer ID) {
		this.ID = ID;
	}

	public Documento(java.util.Date fecha,
			java.lang.Integer soporteDocumentoID,
			java.util.Date fechaNotificacion,
			java.lang.String modoNotificacion,
			java.lang.String numeroDocumento,
			java.lang.String personaNotificacion,
			java.lang.String observacionNotificacion,
			java.lang.String IDRepositorioDocumentos,
			java.lang.String IDPersonaNotificacion,
			java.lang.Integer autorizacionDocumentoID,
			java.lang.String tipoIDPersonaAutorizacion,
			java.lang.String IDPersonaAutorizacion,
			java.lang.String personaAutorizacion, java.lang.String usuarioLog,
			java.util.Date fechaLog, java.lang.Integer ID) {
		this.fecha = fecha;
		this.soporteDocumentoID = soporteDocumentoID;
		this.fechaNotificacion = fechaNotificacion;
		this.modoNotificacion = modoNotificacion;
		this.numeroDocumento = numeroDocumento;
		this.personaNotificacion = personaNotificacion;
		this.observacionNotificacion = observacionNotificacion;
		this.IDRepositorioDocumentos = IDRepositorioDocumentos;
		this.IDPersonaNotificacion = IDPersonaNotificacion;
		this.autorizacionDocumentoID = autorizacionDocumentoID;
		this.tipoIDPersonaAutorizacion = tipoIDPersonaAutorizacion;
		this.IDPersonaAutorizacion = IDPersonaAutorizacion;
		this.personaAutorizacion = personaAutorizacion;
		this.usuarioLog = usuarioLog;
		this.fechaLog = fechaLog;
		this.ID = ID;
	}

}