package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Predio_Persona implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Tipo de Persona")
	private java.lang.String tipoPersona;
	@org.kie.api.definition.type.Label("Numero de Documento")
	private java.lang.String numeroDocumento;
	@org.kie.api.definition.type.Label("Identificador")
	private java.lang.Integer ID;
	@org.kie.api.definition.type.Label("Digito de Verificacion")
	private java.lang.Integer digitoVerificacion;
	@org.kie.api.definition.type.Label("NIT")
	private java.lang.String numeroNit;

	public Predio_Persona() {
	}

	public java.lang.String getTipoPersona() {
		return this.tipoPersona;
	}

	public void setTipoPersona(java.lang.String tipoPersona) {
		this.tipoPersona = tipoPersona;
	}

	public java.lang.String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(java.lang.String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	public java.lang.Integer getID() {
		return this.ID;
	}

	public void setID(java.lang.Integer ID) {
		this.ID = ID;
	}

	public java.lang.Integer getDigitoVerificacion() {
		return this.digitoVerificacion;
	}

	public void setDigitoVerificacion(java.lang.Integer digitoVerificacion) {
		this.digitoVerificacion = digitoVerificacion;
	}

	public java.lang.String getNumeroNit() {
		return this.numeroNit;
	}

	public void setNumeroNit(java.lang.String numeroNit) {
		this.numeroNit = numeroNit;
	}

	public Predio_Persona(java.lang.String tipoPersona,
			java.lang.String numeroDocumento, java.lang.Integer ID,
			java.lang.Integer digitoVerificacion, java.lang.String numeroNit) {
		this.tipoPersona = tipoPersona;
		this.numeroDocumento = numeroDocumento;
		this.ID = ID;
		this.digitoVerificacion = digitoVerificacion;
		this.numeroNit = numeroNit;
	}

}