package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("Pruebas Predio")
public class Predio implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Departamento")
	private java.lang.String departamentoCodigo;
	@org.kie.api.definition.type.Label("Municipio")
	private java.lang.String municipioCodigo;
	@org.kie.api.definition.type.Label("Numero Predial")
	private java.lang.String numeroPredial;
	@org.kie.api.definition.type.Label("Informacion Ingreso Usuario")
	private java.lang.String usuarioLog;
	@org.kie.api.definition.type.Label("Control Fecha Ingreso")
	private java.util.Date fechaLog;

	@org.kie.api.definition.type.Label("Identificador Predio")
	private java.lang.Integer ID;

	@org.kie.api.definition.type.Label("Nombre Territorial")
	private java.lang.String territorial;

	@org.kie.api.definition.type.Label("Unidad Operativa Catastral")
	private java.lang.String uoc;

	@org.kie.api.definition.type.Label("Numero de Matricula")
	private java.lang.String numeroMatricula;

	@org.kie.api.definition.type.Label("NUPRE")
	private java.lang.String nupre;

	@org.kie.api.definition.type.Label(value = "Código Homologado")
	private java.lang.String codigoHomologado;

	public Predio() {
	}

	public java.lang.String getDepartamentoCodigo() {
		return this.departamentoCodigo;
	}

	public void setDepartamentoCodigo(java.lang.String departamentoCodigo) {
		this.departamentoCodigo = departamentoCodigo;
	}

	public java.lang.String getMunicipioCodigo() {
		return this.municipioCodigo;
	}

	public void setMunicipioCodigo(java.lang.String municipioCodigo) {
		this.municipioCodigo = municipioCodigo;
	}

	public java.lang.String getNumeroPredial() {
		return this.numeroPredial;
	}

	public void setNumeroPredial(java.lang.String numeroPredial) {
		this.numeroPredial = numeroPredial;
	}

	public java.lang.String getUsuarioLog() {
		return this.usuarioLog;
	}

	public void setUsuarioLog(java.lang.String usuarioLog) {
		this.usuarioLog = usuarioLog;
	}

	public java.util.Date getFechaLog() {
		return this.fechaLog;
	}

	public void setFechaLog(java.util.Date fechaLog) {
		this.fechaLog = fechaLog;
	}

	public java.lang.Integer getID() {
		return this.ID;
	}

	public void setID(java.lang.Integer ID) {
		this.ID = ID;
	}

	public java.lang.String getTerritorial() {
		return this.territorial;
	}

	public void setTerritorial(java.lang.String territorial) {
		this.territorial = territorial;
	}

	public java.lang.String getUoc() {
		return this.uoc;
	}

	public void setUoc(java.lang.String uoc) {
		this.uoc = uoc;
	}

	public java.lang.String getNumeroMatricula() {
		return this.numeroMatricula;
	}

	public void setNumeroMatricula(java.lang.String numeroMatricula) {
		this.numeroMatricula = numeroMatricula;
	}

	public java.lang.String getNupre() {
		return this.nupre;
	}

	public void setNupre(java.lang.String nupre) {
		this.nupre = nupre;
	}

	public java.lang.String getCodigoHomologado() {
		return this.codigoHomologado;
	}

	public void setCodigoHomologado(java.lang.String codigoHomologado) {
		this.codigoHomologado = codigoHomologado;
	}

	public Predio(java.lang.String departamentoCodigo,
			java.lang.String municipioCodigo, java.lang.String numeroPredial,
			java.lang.String usuarioLog, java.util.Date fechaLog,
			java.lang.Integer ID, java.lang.String territorial,
			java.lang.String uoc, java.lang.String numeroMatricula,
			java.lang.String nupre, java.lang.String codigoHomologado) {
		this.departamentoCodigo = departamentoCodigo;
		this.municipioCodigo = municipioCodigo;
		this.numeroPredial = numeroPredial;
		this.usuarioLog = usuarioLog;
		this.fechaLog = fechaLog;
		this.ID = ID;
		this.territorial = territorial;
		this.uoc = uoc;
		this.numeroMatricula = numeroMatricula;
		this.nupre = nupre;
		this.codigoHomologado = codigoHomologado;
	}

}