package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Solicitante implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Identificador Solicitud")
	private java.lang.Integer solicitudID;
	@org.kie.api.definition.type.Label("Tipo de Persona")
	private java.lang.String tipoPersona;
	@org.kie.api.definition.type.Label("Tipo Documento")
	private java.lang.String tipoIdentificacion;
	@org.kie.api.definition.type.Label("Numero de documento")
	private java.lang.String numeroIdentificacion;
	@org.kie.api.definition.type.Label("Digito de Verificacion")
	private java.lang.String digitoVerificacion;
	@org.kie.api.definition.type.Label("Primer Nombre")
	private java.lang.String primerNombre;
	@org.kie.api.definition.type.Label("Primer Apellido")
	private java.lang.String primerApellido;
	@org.kie.api.definition.type.Label("Razon Social")
	private java.lang.String razonSocial;
	@org.kie.api.definition.type.Label("Departamento")
	private java.lang.String direccionDepartamentoCodigo;
	@org.kie.api.definition.type.Label("Municipio")
	private java.lang.String direccionMunicipioCodigo;
	@org.kie.api.definition.type.Label("Informacion de Ingreso Usuario")
	private java.lang.String usuarioLog;
	@org.kie.api.definition.type.Label("Informacion fecha Ingreso")
	private java.util.Date fechaLog;
	@org.kie.api.definition.type.Label("identificacdor Solicitante")
	private java.lang.Integer ID;

	@org.kie.api.definition.type.Label("Numero Nit")
	private java.lang.String nit;

	public Solicitante() {
	}

	public java.lang.Integer getSolicitudID() {
		return this.solicitudID;
	}

	public void setSolicitudID(java.lang.Integer solicitudID) {
		this.solicitudID = solicitudID;
	}

	public java.lang.String getTipoPersona() {
		return this.tipoPersona;
	}

	public void setTipoPersona(java.lang.String tipoPersona) {
		this.tipoPersona = tipoPersona;
	}

	public java.lang.String getTipoIdentificacion() {
		return this.tipoIdentificacion;
	}

	public void setTipoIdentificacion(java.lang.String tipoIdentificacion) {
		this.tipoIdentificacion = tipoIdentificacion;
	}

	public java.lang.String getNumeroIdentificacion() {
		return this.numeroIdentificacion;
	}

	public void setNumeroIdentificacion(java.lang.String numeroIdentificacion) {
		this.numeroIdentificacion = numeroIdentificacion;
	}

	public java.lang.String getDigitoVerificacion() {
		return this.digitoVerificacion;
	}

	public void setDigitoVerificacion(java.lang.String digitoVerificacion) {
		this.digitoVerificacion = digitoVerificacion;
	}

	public java.lang.String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(java.lang.String primerNombre) {
		this.primerNombre = primerNombre;
	}

	public java.lang.String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(java.lang.String primerApellido) {
		this.primerApellido = primerApellido;
	}

	public java.lang.String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(java.lang.String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public java.lang.String getDireccionDepartamentoCodigo() {
		return this.direccionDepartamentoCodigo;
	}

	public void setDireccionDepartamentoCodigo(
			java.lang.String direccionDepartamentoCodigo) {
		this.direccionDepartamentoCodigo = direccionDepartamentoCodigo;
	}

	public java.lang.String getDireccionMunicipioCodigo() {
		return this.direccionMunicipioCodigo;
	}

	public void setDireccionMunicipioCodigo(
			java.lang.String direccionMunicipioCodigo) {
		this.direccionMunicipioCodigo = direccionMunicipioCodigo;
	}

	public java.lang.String getUsuarioLog() {
		return this.usuarioLog;
	}

	public void setUsuarioLog(java.lang.String usuarioLog) {
		this.usuarioLog = usuarioLog;
	}

	public java.util.Date getFechaLog() {
		return this.fechaLog;
	}

	public void setFechaLog(java.util.Date fechaLog) {
		this.fechaLog = fechaLog;
	}

	public java.lang.Integer getID() {
		return this.ID;
	}

	public void setID(java.lang.Integer ID) {
		this.ID = ID;
	}

	public java.lang.String getNit() {
		return this.nit;
	}

	public void setNit(java.lang.String nit) {
		this.nit = nit;
	}

	public Solicitante(java.lang.Integer solicitudID,
			java.lang.String tipoPersona, java.lang.String tipoIdentificacion,
			java.lang.String numeroIdentificacion,
			java.lang.String digitoVerificacion, java.lang.String primerNombre,
			java.lang.String primerApellido, java.lang.String razonSocial,
			java.lang.String direccionDepartamentoCodigo,
			java.lang.String direccionMunicipioCodigo,
			java.lang.String usuarioLog, java.util.Date fechaLog,
			java.lang.Integer ID, java.lang.String nit) {
		this.solicitudID = solicitudID;
		this.tipoPersona = tipoPersona;
		this.tipoIdentificacion = tipoIdentificacion;
		this.numeroIdentificacion = numeroIdentificacion;
		this.digitoVerificacion = digitoVerificacion;
		this.primerNombre = primerNombre;
		this.primerApellido = primerApellido;
		this.razonSocial = razonSocial;
		this.direccionDepartamentoCodigo = direccionDepartamentoCodigo;
		this.direccionMunicipioCodigo = direccionMunicipioCodigo;
		this.usuarioLog = usuarioLog;
		this.fechaLog = fechaLog;
		this.ID = ID;
		this.nit = nit;
	}

}